Import('env', 'plugins')

plugins += env.SharedLibrary('dipole',
	['dipole.cpp', 'irrproc.cpp', 'irrtree.cpp', 'bluenoise.cpp'])

plugins += env.SharedLibrary('betterdipole',
	['betterdipole.cpp', 'irrproc.cpp', 'irrtree.cpp', 'bluenoise.cpp'])

Export('plugins')
