Import('env', 'plugins')

plugins += env.SharedLibrary('dipole', 
	['dipole.cpp', 'irrproc.cpp', 'irrtree.cpp'])

plugins += env.SharedLibrary('fibershader', 
	['fibershader.cpp'])

Export('plugins')
